# .markdownlint.yaml
MD013:
  line_length: 120   # â† set your preferred limit (e.g., 100 or 120)
  heading_line_length: 120
  code_block_line_length: 0  # ignore long lines in code blocks
  tables: false               # ignore tables if desired
